// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTPaperTag = "t_paper_tags"

// TPaperTag mapped from table <t_paper_tags>
type TPaperTag struct {
	ID      int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 主键
	PaperID int32 `gorm:"column:paper_id;not null" json:"paper_id"`          // paper主键
	TagID   int32 `gorm:"column:tag_id;not null" json:"tag_id"`              // 主键
}

// TableName TPaperTag's table name
func (*TPaperTag) TableName() string {
	return TableNameTPaperTag
}
