// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTPaper = "t_papers"

// TPaper mapped from table <t_papers>
type TPaper struct {
	ID            int32      `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                         // 主键
	Address       *string    `gorm:"column:address" json:"address"`                                             // 文章地址
	Title         string     `gorm:"column:title;not null" json:"title"`                                        // 文章英文标题
	TitleCh       string     `gorm:"column:title_ch;not null" json:"title_ch"`                                  // 文章中文标题
	Authors       *string    `gorm:"column:authors" json:"authors"`                                             // 作者
	PublishedTime time.Time  `gorm:"column:published_time;not null" json:"published_time"`                      // 发布时间
	Summary       *string    `gorm:"column:summary" json:"summary"`                                             // 英文文概括
	SummaryCh     *string    `gorm:"column:summary_ch" json:"summary_ch"`                                       // 中文概括
	Categories    *string    `gorm:"column:categories" json:"categories"`                                       // 阅读数量
	Filepath      *string    `gorm:"column:filepath" json:"filepath"`                                           // 文件名
	Read          int32      `gorm:"column:read;not null" json:"read"`                                          // 阅读数量
	Favorite      int32      `gorm:"column:favorite;not null" json:"favorite"`                                  // 收藏数量
	FulltextCh    *string    `gorm:"column:fulltext_ch" json:"fulltext_ch"`                                     // 我也不知道是啥
	CreatedAt     *time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP(3)" json:"created_at"` // 创建时间
	UpdatedAt     *time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP(3)" json:"updated_at"` // 更新时间
}

// TableName TPaper's table name
func (*TPaper) TableName() string {
	return TableNameTPaper
}
