// Code generated by repo.io/gen. DO NOT EDIT.
// Code generated by repo.io/gen. DO NOT EDIT.
// Code generated by repo.io/gen. DO NOT EDIT.

package model

const TableNameTag = "tags"

// Tag mapped from table <tags>
type Tag struct {
	ID       int32  `gorm:"column:id" json:"id"`
	Name     string `gorm:"column:name" json:"name"`
	ParentID int32  `gorm:"column:parent_id" json:"parent_id"`
}

// TableName Tag's table name
func (*Tag) TableName() string {
	return TableNameTag
}
