// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Austin-Cheng/EnjoyableReading/adapter/driven/repo/impl"
	"github.com/Austin-Cheng/EnjoyableReading/adapter/driver"
	"github.com/Austin-Cheng/EnjoyableReading/adapter/driver/controllers/papers"
	"github.com/Austin-Cheng/EnjoyableReading/adapter/driver/controllers/tags"
	"github.com/Austin-Cheng/EnjoyableReading/common/settings"
	impl3 "github.com/Austin-Cheng/EnjoyableReading/domain/paper/impl"
	impl2 "github.com/Austin-Cheng/EnjoyableReading/domain/tag/impl"
	"github.com/Austin-Cheng/EnjoyableReading/infrastructure/repository/db"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp(conf *settings.Config) (*AppRunner, func(), error) {
	data, cleanup, err := db.NewClient()
	if err != nil {
		return nil, nil, err
	}
	gormDB := db.NewDB(data)
	tag := impl.NewTag(gormDB)
	useCase := impl2.NewTag(tag)
	service := tags.NewService(useCase)
	paper := impl.NewPaper(gormDB)
	paperUseCase := impl3.NewPaper(paper)
	papersService := papers.NewService(paperUseCase)
	router := driver.Router{
		TagController:   service,
		PaperController: papersService,
	}
	server := driver.NewHttpServer(router)
	app := newApp(server)
	appRunner := &AppRunner{
		App: app,
	}
	return appRunner, func() {
		cleanup()
	}, nil
}

// wire.go:

var appSet = wire.NewSet(
	newApp, wire.NewSet(wire.Struct(new(AppRunner), "*")),
)
