server:
  name: "${{SERVER_NAME}}"
  http:
    addr: 0.0.0.0:8280
    timeout: 1s
    innerHost: 127.0.0.1
  doc:
    host: 0.0.0.0:8280
    version: "1.0"

database:
  dbtype: mysql
  host: "${DB_HOST}"
  username: "${DB_USERNAME}"
  password: "${DB_PASSWORD}"
  database: "${DB_NAME}"
  max-idle-connections: 5
  max-open-connections: 50
  max-connection-life-time: 300
  loglevel: 2
  isdebug: true
  tableprefix: t_

logs:
  - name: basic_bigdata_service
    default: true
    enable_caller: true
    stacktrace_level: error
    development: false
    cores:
      - destination: /data/logs/info.log        #日志输出地址
        rotate_size: 100MB                      #文件分割尺寸
        core_type: file                         #core类型，file, stdout两种
        enable_color: false                     #是否开启输出颜色
        output_format: json                     #日志输出的格式, json, console
        log_level: info                         #该日志流的等级
      - destination: /data/logs/error.log
        rotate_size: 100MB
        core_type: file
        output_format: json
        log_level: error
      - destination: console
        core_type: stdout
        output_format: console
        enable_color: true
        log_level: info